version: '3.8'
services:

  api:
    container_name: rcm_api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ./
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: rcm-username
      POSTGRES_PASSWORD: rcm-password
      POSTGRES_DB: rcm
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local